parameters:
    database_host: OSU-MSSQL02
    database_port: 1433
    database_name: OfficeAdmin
    database_user: ~
    database_password: ~
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: 8f16ad448aae9c5d1e9371223425b7ef
    database_path: null
